# Veritabani Ayarlari (KESIN COZUM)
quarkus.datasource.db-kind=clickhouse
quarkus.datasource.username=nifi_user
quarkus.datasource.password=123456

# URL'de ':http:' ifadesini ekleyerek protokolü garantiye aliyoruz
quarkus.datasource.jdbc.url=jdbc:clickhouse:http://localhost:8123/default?compress=false

# Baglanti Havuzu (Hatalari yutmamasi icin)
quarkus.datasource.jdbc.max-size=16
quarkus.datasource.jdbc.min-size=2
quarkus.datasource.jdbc.acquisition-timeout=5
quarkus.elasticsearch.hosts=localhost:9200
